print("===========================")
print("      DEVELOPER PROFILE")
print("===========================")
print()
print("Name        : ")
print("Education   : ")
print("Role Goal   : AI Engineer")
print("Skills      : Python (Learning)")
print("Country     : ")
print()
print("Thank you!")